---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-7
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[iisnode::default]
    attributes:
