---
driver:
  name: vagrant

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: windows-7
  - name: windows-8
  - name: windows-8.1
  - name: windows-10
  - name: windows-2008r2
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[iisnode::default]
